In [ ]:
import torch

In [ ]:
x = torch.arange(4.0)
x

In [ ]:
x.requires_grad_(True)
x.grad

In [ ]:
y = 2 * torch.dot(x,x)
y # grad_fn=<MulBackward0> -> calculation graph

In [ ]:
y.backward()

In [11]:
x.grad, x.grad == 4 * x

(tensor([ 0.,  4.,  8., 12.]), tensor([True, True, True, True]))

In [13]:
x.grad.zero_() #clean previous grad, _ is rewrite 
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [15]:
x.grad.zero_()
y = x * x
y.sum().backward() # y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

In [19]:
# fix some parameters:
x.grad.zero_()
y = x * x
u = y.detach() # u is scalar here 
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [20]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])