In [ ]:
import torch

In [ ]:
x = torch.arange(12)
x

In [ ]:
x.shape
x.reshape([3,4])

In [ ]:
torch.zeros((2,3,4))

In [ ]:
torch.tensor([[1,2,3,4],[2,3,4,1],[4,3,2,1]]).shape

In [ ]:
# calculate by element
# a = torch.tensor([2,3,4])
a = torch.tensor([2.0,3,4])
b = torch.tensor([4,5,6])
a+b, a-b, a*b, a/b, a**b
# Integer division of tensors using div or / is no longer supported, true_division is //. change int to float

In [14]:
# concat
torch.cat((a,b),dim=0)

tensor([2., 3., 4., 4., 5., 6.])

In [15]:
# bool
a == b

tensor([False, False, False])

In [16]:
# broadcasting mechanism
c = torch.arange(3).reshape((3,1))
d = torch.arange(2).reshape((1,2))
c + d # shape should be (3,2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
before = id(b) # id is like point in C++
b = a+b
print(id(b) == before) #arrange a new memory
medium = id(b)
# in-place:if don't need reuse b in future function
b[:] = a+b # or b += a
print(id(b) == medium)

False
True


In [20]:
# convert with numpy
A = a.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [21]:
# convert to python scala
e = torch.tensor([3.5])
e, e.item(), float(e), int(e)

(tensor([3.5000]), 3.5, 3.5, 3)

In [34]:
#data preprocessing
import os
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n') # column
    f.write('NA, Pave, 127500\n')
    f.write('2,NA, 106000\n') # NA can't has space' '
    f.write('4,NA, 178100\n')
    f.write('NA,NA, 140000\n')

In [35]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


In [36]:
inputs, output = data.iloc[:,:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley
0       3.0   Pave
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN


In [37]:
# one hot
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms   Alley_ Pave   Alley_nan
0       3.0             1           0
1       2.0             0           1
2       4.0             0           1
3       3.0             0           1

In [39]:
X, y = torch.tensor(inputs.values), torch.tensor(output.values)
X, y 
# float64 is slow during training, so better choose float32

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))